### ISSUE TITLE
Improve keyboard handling for UTF8 and other encodings

### ISSUE THREAD

**Issue by eugeneloza** [eugeneloza/castle-engine#54]
/As the issue is getting larger I'll try to copy everything here/

> eugeneloza - Today at 8:11 AM
> It looks like I am unable to input Russian/Ukrainian characters into TCastleEdit (while its default is AllChars)...?
> 
> michalis - Today at 10:06 AM
> @eugeneloza The input of Russian/Ukrainian probably fails because we currently limit the input to things that can be expressed as Pascal "char". In particular, TInputPressRelease.KeyCharacter is a "char", along with some related properties. I'm guessing that some Russian/Ukrainian characters can only be expressed as multi-byte sequences in UTF-8, and thus they can be only expressed as AnsiString, not "char", in TInputPressRelease. Pull requests to fix this are welcome, of course -- please keep the TInputPressRelease.KeyCharacter working as char (for compatibility), but also add something like TInputPressRelease.KeyString: string that can express the typed character as a string (encoded using UTF-8, as all strings in CGE). Various CastleWindow backends will need to be adjusted to actually pass some useful content for KeyString.
> 
> eugeneloza - Today at 10:07 AM
> Hmmm...  Cyrillic keypresses don't generate OnPress at all!
> Testing: OnPress for Cyrillic is generated in Windows but not in Linux
> Ok. I finally get it. In Windows we receive 1-byte Win1251 char, and in Linux - UTF8 char, which is longer than 1 and therefore dropped. Not as easy as I'd think, I'll try to get how to extract the current OS encoding in Windows...
> Ok. That seems to be relatively easy to do in GTK, but I'm really unsure how to fix that in Windows. I only wonder, why GTK reports Cyrillic keypresses as K_None... hmm... I might have an idea.
> 
> michalis - Today at 1:57 PM
> @eugeneloza The TKey enumeration does not support all the possible characters. It is supposed to be used to represent "physical keys", not characters. So it's normal that some combinations may result in TKey=K_None, but with some meaningful character.
> Indeed, as you found out, solving this requires dealing with encoding. You need to extract the key string as UTF-8. Lazarus does it too, so there must be a way (and you can probably peek how in Lazarus sources :smiley: ).
> eugeneloza - Today at 2:00 PM
> @michalis should I modify GdkKeysymToKey to do that (yes, it has the corresponding keys of Cyrillic and other alphabets)? E.g. we can secure that GDK is always mapped at correct Latin keys (e.g. Russian Ы = Ukrainian і = keyboard s key)? This would create a huge case but should preform nicely - while returning the correct string for each native letter it will not break game controls which are bound to Latin keys and will require no modifications of Key_***. WDYT?
> (Thou I'll be able to map only keyboard keys I'm aware of: Not Arabic or similar)
> Or we may use Event^.hardware_keycode, thou I am unsure how it will behave on different hardware
> michalis - Today at 2:09 PM
> @eugeneloza No, definitely not. Do not try to calculate the character/string yourself, by analyzing the keys user pressed. GTK should provide you the information about the pressed character (as PChar), and it knows the user configured preferences, language, user preferred languages modifier key etc. Moreover, you do not want to modify the generated TKey at all -- the TKey does not, and should not, describe local characters.
> @eugeneloza Briefly looking, this information is probably inside the string and length fields of GdkEventKey structure. We get this in signal_key_press_event and signal_key_release_event.(edited)

**Comment by eugeneloza** [comment]
Ok. Analyzing `Key := GdkKeysymToKey(Event^.KeyVal);` it just processes `Event^.KeyVal` which is almost a unicode character (actually `gdk_keyval_to_unicode(Event^.KeyVal)` is a unicode character number). So, basically this is why it returns `K_None` (as non-latin unicode characters aren't mapped anywhere).
We have three options here:
1. Remap all possible non-latin variants of unicode characters. This will surely go wild in case of different keys mapping (e.g. at least there are several Russian keys layout (like QWERTY and AZERTY for English), hardly any other than ЙЦУКЕН is used, but this can actually be different).
2. Try using `Event^.hardware_keycode` and remapping them to `Key_...`. I can't find any sort of documentation on how to do that properly (i.e. can hardware keycodes be different at different hardware?). It returns equal codes for the key pressed regardless of current input language.
3. Leave everything "as is" and just use `Event^._string` as a valid UTF8 representation of the key event. This will disable player control if the input locale has changed. Thou GIMP itself suffers from this issue :)

If I can figure out how to do "2" fail-proof, that would be the best option to my idea, but I am unsure yet. Thinking.

**Comment by michaliskambi** [comment]
I have to say I definitely prefer 3. :)

We should just use the UTF-8 string provided by GTK, and place it in `TInputPressRelease.KeyString: string`. We definitely should *not* try to construct it ourselves through any other means. The GTK folks have done a large job, doing it as-correctly-as-possible for all the possible languages. Moreover, the GTK knows user preferences (language, keyboard layout, preferred key to input accented letters etc.), while we don't.

We definitely do not want a solution that works for some specific languages. We want a solution that just works for all the languages, for all the possible user preferences. Using what GTK gives us is the only approach here, in my opinion.

Lazarus is also doing it (see Lazarus sources, `lcl/interfaces/gtk2/gtk2proc.inc` , they use `gdk_event_key_set_string` that actually just takes `Event^._String`).

For other backends, the same approach is true. The API of the windowing system (like WinAPI on Windows) has to provide us this string. We may need to change encoding to UTF-8, but that's all we should have to do.

**Comment by eugeneloza** [comment]
Well, the problem is that it will work for string input, but not for game control.
Let's imagine a simple situation, when the player writes his character name in Czech and starts the game and whooooops... he can't move forward, because "w" key is now "ü" (while ASD are working) - he'll just be getting `key_none` as it's not mapped. Gives me much irritation in GIMP when after typing a text in Ukrainian I can no longer press Ctrl+Z or use any other key.

**Comment by michaliskambi** [comment]
1. Can you explain in more detail what is the method of inputting local characters in Czech? I want to understand this problem better.

      In Polish, one helds an "Alt" key (although this is configurable) and then some letters turn into other letters (e.g. "A" changes into "Ą"). To write normal "A", you just release the "Alt" key. Does in Czech you press some "persistent" key?

2. In any case, whatever the input method is --- we should use it. Users know it, and it is already implemented in GTK (and WinAPI, and other systems). If GTK is implementing it, then all the software is using it, I guess.

    I don't think we realistically *can* implement our own input method for all the languages in the world. And I don't think we should even try, it seems to me like a huge task that we have no way of realistically completing.

    And we are a game engine, not a "windowing system" like GTK or Windows. We do not have an infrastructure to store some system-wide preferences (like "whether user prefers to use "Alt" key, or "Windows" key, to type Polish characters). And we do not want to have such infrastructure (every Castle Game Engine game should be a separate entity).

So, I'm afraid that even if GTK (or WinAPI or any other) input method is not optimal, we should just use it.

**Comment by eugeneloza** [comment]
Well, I'm speaking exactly that we need to use GTK input because it actually handles all the codepage conversions correctly. Just to understand how to.

I believe `gdk_keymap_translate_keyboard_state` is what we need here.
https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html#gdk-keymap-translate-keyboard-state
However, nobody would care to say how to use that in a practical case? Why won't anybody say if `hardware_keycode` is always the same for the same "QWERTY" keyboards or not? Looks like it is, but there is no direct answer neither in GTK documentation, nor at Linux forums. If it is, then securing mapping the same keys to same English letters is a piece of cake.

And 
```
gdk_keymap_translate_keyboard_state(
     gdk_keymap_get_for_display(gdk_display_get_default{gdk_window_get_display(Event^.window)}),
     Event^.hardware_keycode, Event^._type, Event^.group, @Event^.keyval, group, level, modif); 
```
returns some stupid result while the required `gdk_window_get_display` is absent from `gdk2` unit... ugh...

> In Polish, one helds an "Alt" key (although this is configurable) and then some letters turn into other letters (e.g. "A" changes into "Ą"). To write normal "A", you just release the "Alt" key. Does in Czech you press some "persistent" key?

1.
I'm unsure about Czech :) In Ukrainian I have "keyboard layouts" - three of those. And when I press Shift+Alt I switch between English->Russian->Ukrainian layouts (completely removing English keys and starting typing Cyrillic - different chars may be mapped to the same key, e.g. English "]" becomes Russian "Ъ" and then Ukrainian "Ї"). Some keyboards like German, Azerbaidzhan or even French also have this pattern. E.g. this is how German layout looks like:
https://i.stack.imgur.com/nzeZQ.png - Note umlaut letters in the right part and QWERTZ layout.
In Ukrainian it looks even weirder:
https://i.stack.imgur.com/ILbD2.png - the key highlighted by red is located in different regions (may be top or down, right or left part of the keyboard) or may be absent at all (and needs special commands like through "Alt" way you've described above).

2. Actually we **do implement** our own input method in `Castle_window_gtk.inc` as `GdkKeysymToKey(GdkKeysym: guint): TKey;` procedure which returns `KeyNone` for non-English layouts. I'm speaking of this one. I.e. mapping `GdkKeysym` to `TKey`.
In current situation it will work only for QWERTY keyboard layout, but will fail dramatically for AZERTY French layout (e.g. WASD keys mapped to movement will now have a very different location).

Right now, let's try doing something with GTK. We can always give up and fall back only to getting UTF8 characters as strings (`Event^._string` does that perfectly already). And yeah, after reading the useless documentation and forums half of the day I'm nearly ready to :) But yet it's too early to.

Windows has a different problem - codepages changing with the layout (UTF8 is UTF8, but e.g. Russian&Ukrainian codepage is Windows1251 and Windows1253 for Greek or Windows1256 for Arabic - i.e. the same KeyValues will correspond to different symbols typed in (and therefore we need to know current keyboard layout->encoding to convert it to UTF8 correctly)). However, I don't know how to solve it either :)

**Comment by eugeneloza** [comment]
I'm not sure about the note on MBCS encoding. Googling shows me it's Windows-related (while GTK, while can be run under Windows, but is rather Linux feature, e.g. we can make sure it's Linux through compiler directive or fall back to previous condition and do without locale support in extremely rare case of GTK in Windows system).

**Comment by eugeneloza** [comment]
(Only now I realize how perfectly CGE is documented in contrast to FPC or GDK :D)

**Comment by eugeneloza** [comment]
A bit off-topic. I've met some Polish comments throughout the Engine, including in GTK include file, I think I can translate those into English (I can read Polish as it's very similar to Ukrainian :)). WDYT? Of course, I'll leave them for you to acknowledge, in case I misunderstand something.

**Comment by michaliskambi** [comment]
As for the check: Yes, just replace the check "CharKey <> #0" with "KeyString <> nil". When either `KeyString <> nil` or when `Key <> K_None`, we can make DoKeyDown. This is the simple solution I desire:)

As for Polish comments: Indeed, in the ancient times I placed some comments in Polish. When you see them, it means that
1. you're looking at some really old Castle Game Engine code :),
2. yes, translating them to English is very welcome! In some cases, they may be simply outdated (or just "not really that important") and simply deleting these comments may be OK too.

**Comment by eugeneloza** [comment]
> KeyString <> nil

Emm... I'm not really sure if I understand what exactly this statement mean. As far as I understand, setting `SomeString := nil` will efficiently free the string content due to reference counting for managed types. But as for checking `<> nil` I am unsure if this is fail-proof. I've investigated the question and it seems that `SomeString <> ''` or `length(SomeString) = 0` are used to check if the string is empty (and both should produce the same code). Are you sure about `nil`?

**Comment by michaliskambi** [comment]
Yes, I meant `KeyString <> ''`, sorry :)

I was thinking about PChar (equivalent of `char*` in C), which is most probably the type of `Event^._String` from GDK. But of course you should assign it to a Pascal string as soon as possible, and then check `KeyString <> ''`.

You cannot do `S := nil` or compare `S <> nil` with AnsiStrings at all.

**Comment by eugeneloza** [comment]
@michaliskambi, there are 4 questions in this commit: https://github.com/eugeneloza/castle-engine/commit/710bde0d713ba1fe4d4ec42c5d6bce3b5c32c228 I'd appreciate your comments on those. Actually they are two, not 4. 1) The check "if the key was pressed" is made by checking `KeyChar`, which will work incorrectly for longer UTF8 characters. 2) Passing #0 char (and string) to input event seems fine, thou I'm not certain why it is made, so I'd prefer to ask :)

**Comment by eugeneloza** [comment]
/todo for tomorrow or some nearest future/
1. Make `CharKey` a `function... Result := StringKey[0]` and pass only `StringKey` (to simplify API)
2. Fix CastleComponents compilation (first of all, `KeyLCLToCastle` function). Ugh... why is `key: word`? An UTF8 char may be longer than 16 bit.
3. Fix Windows compilation
4. Fix all other instances of compilation & test whatever possible.
5. Get Windows keyboard encoding
6. Convert Windows keyboard encoding to UTF8
7. Replace `KeyChar` with `KeyString` where applicable (`TCastleEdit` first of all).

**Comment by michaliskambi** [comment]
> 1) The check "if the key was pressed" is made by checking KeyChar, which will work incorrectly for longer UTF8 characters. 

The idea is to pass only `KeyString` (of `string` type) around in the internal engine routines. And check `KeyString <> ''`. Do not pass key as `char` anymore.

Only for compatibility, keep TInputPressRelease.KeyCharacter defined, and it should be a simple function now:

```
function TInputPressRelease.KeyCharacter: string;
begin
  if Length(KeyString) = 1 then
    Result := KeyString[1]
  else
    Result := #0;
end;
```

To keep the `TKeysPressed` working, you will also want to convert key as string -> key as char, using the same algorithm as above.

(Note: I would not advice to extend `TKeysPressed` to remember all possible UTF-8 input within the first PR, this would complicate stuff, and most use-cases don't need it. E.g. TCastleEdit can receive UTF-8 input without it. It's simpler to leave `TKeysPressed` to only remember the presses of simple keys (that can be expressed as TKey or char) for now, and worry about this in later PR.)

> 2) Passing #0 char (and string) to input event seems fine, thou I'm not certain why it is made, so I'd prefer to ask :)

Do not use string with contents `#0`. While it will work in Pascal, it would unnecessarily complicate the interface, forcing you to sometimes check `(KeyString <> '') or (KeyString <> #0)`. We don't want that :) When the key cannot be express as string, then the KeyString is '', and KeyCharacter is #0. These are the commonly used "default" values for string (in case of KeyString) and char (in case of KeyCharacter).

**Comment by eugeneloza** [comment]
**Todo**: `TCastleControlCustom.KeyDown` and `TCastleWindowCustom.OpenGLControlKeyDown` don't use UTF8 for now and is limited to `char`. There doesn't seem to be any simple way to handle this issue unless we can catch `IntfUtf8KeyPress` (see http://wiki.freepascal.org/LCL_Key_Handling - but unfortunately I'm not even close to understand what it means in practice). On the other hand, at the moment it's very unlikely for the user to use `TCastleEdit` or similar elements on a Lazarus form, when `TEdit` exists.
However, it'll become an important issue, when a visual editor will be up and running (i.e. `TCastleControl` usually taking up most of `TForm` functional).

**Comment by michaliskambi** [comment]
To use X11 backend:

Define symbol `CASTLE_WINDOW_XLIB` anywhere (e.g. in your fpc.cfg, or in castleconf.inc) to compile CastleWindow using X11 backend. Same is true for any other CastleWindow backend. By default CastleWindow selects the "best" backend, but you can switch it.

Note that adding UTF-8 to X11 is quite low-priority probably. Not many people are using it probably. Just make sure it compiles OK.

TCastleEdit likes UTF8 characters! :) I don't see any special problem. Once you add `KeyString` (string, UTF-8 encoded) to `TInputPressRelease`, then TCastleEdit.Press should be able to just do 

```
Text := Text + Event.KeyString;
```

instead of

```
Text := Text + Event.KeyCharacter;
```

Also, change the above condition from

```
     (Event.KeyCharacter <> #0) and
     (Event.KeyCharacter in AllowedChars) and ...
```

to

```
(
  (AllowedChars = AllChars) or 
  ( (Event.KeyCharacter <> #0) and (Event.KeyCharacter in AllowedChars) )
) and ...
```

This will take care of AllowedChars. Using AllowedChars (with other value than default AllChars) implicitly means that you require only normal 8-bit chars. Which is not a problem for typical AllowedChars use-case, which is to limit input to stuff like digits and hyphes or such. (To force user to input a number, or a telephone number or such).

**Comment by eugeneloza** [comment]
Looks like everything is working as expected and stable. I've removed UTF8 support from X11, just made it to compile as you suggested (`Xutf8LookupString` was really too complex for me :)).

Current to-do remaining:
fix `TCastleControlCustom.KeyDown` and `TCastleWindowCustom.OpenGLControlKeyDown` to use `IntfUtf8KeyPress`.
fix `TCastleEdit` in `src/ui/castledialogstates.pas` and `src/ui/castlecontrols_edit.inc`.

**Comment by eugeneloza** [comment]
Ok, so I think I've done everything I could here...
Unfortunately the issue is not 100% covered. I could not make CastleControls to accept UTF8 symbols. Sadly this manual appeared far beyond something I can comprehend and implement: http://wiki.freepascal.org/LCL_Key_Handling (requires manually catching events).

**Done**:
GTK, WinAPI return UTF8 symbols
All Castle Engine routines operate on UTF8 characters correctly
Including `TCastleEdit`
Tested and working in Windows 7 x 64 bit (console), XLib and GTK (console + `TCastleEdit`)

**Partly done**:
`TInputPressRelease.KeyCharacter` is almost a copy of GTK conversion of UTF8 character to a `Char`, thou it might be improved, I guess.
in WinAPI I used a relatively safe, but still dirty trick of `MultiByteToWideChar` which has two issues, both unimportant, but might worth improving in future. Thou it still works a bit buggy with console output of Ukrainian "i" letter (FPC does that too).

**Not done**:
XLib returns only ASCII symbols
CastleComponents return only ASCII symbols

**Comment by michaliskambi** [comment]
The KeyCharacter should be simple and cross-platform, as I suggested earlier, just a method in TInputPressRelease:

```
function TInputPressRelease.KeyCharacter: string;
begin
  if Length(KeyString) = 1 then
    Result := KeyString[1]
  else
    Result := #0;
end;
```

I would prefer to keep it as simple, without using any GTK or WinAPI specials. KeyCharacter is for catching things that can be expressed as ASCII characters, and the above implementation should be sufficient?

**Comment by michaliskambi** [comment]
Ignore my above comment about `TInputPressRelease.KeyCharacter`, what you did is perfect, more comments in PR https://github.com/castle-engine/castle-engine/pull/100/ :)

**Comment by eugeneloza** [comment]
Looks like the issue is fixed (to some extent).
